# swift 抛出错误和异常 Error throw 

1. 抛出错误:

func errortest(astr: String?) throws -> String {
    guard let astr = astr else {
        throw NSError(domain: "com.pflnh", code: 1000, userInfo: [NSLocalizedDescriptionKey:"error"])
    }
    return astr
}

do {
    let astr = try errortest(nil)
    print(astr)
}
catch let error as NSError  {
    print("\(error.localizedDescription)")
}

2. 抛出异常

enum StringError:ErrorType {
    case StringNillError
    case StringSomeError
}

func errortest(astr: String?) throws -> String {
    guard let astr = astr else {
        throw StringError.StringNillError
    }
    return astr
}


do {
    let astr = try errortest(nil)
    print(astr)
}
catch   {
    print("\(error)")
}

